repo_id: null
num_episodes: 100
root: ./datasets
tasks: all
randomize_objects: false
seed: 0
spawn_x_range: [-0.20, 0.20]
spawn_y_range: [0.30, 0.45]
features:  # null for all, or a subset of these keys
  - observation.images.overhead
  - observation.images.wrist
  - observation.state.ee.8dof
  - observation.state.ee.10dof
  - observation.state.ee.8dof_rel
  - observation.state.ee.10dof_rel
  - action.ee.8dof
  - action.ee.10dof
  - action.ee.8dof_rel
  - action.ee.10dof_rel
  - observation.target_bin_onehot
  - observation.target_obj_onehot
  - observation.keypoints_overhead
  - observation.keypoints_wrist
  - observation.target_obj_keypoints_overhead
  - observation.target_bin_keypoints_overhead

hydra:
  job:
    chdir: false
  run:
    dir: .
